services:
  - type: web
    name: devtools-pro-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  - type: worker
    name: devtools-pro-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run bot
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production