services:
  - type: web
    name: phone-validator-api
    env: node
    plan: free
    buildCommand: cd server && npm install && cd ../bot && npm install
    startCommand: bash start-all.sh
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: TELEGRAM_BOT_TOKEN
        value: your-telegram-bot-token
